### ISSUE TITLE
REPL: Research alternatives

### ISSUE THREAD

**Issue by azinit** [feature-sliced/repl#12]
## Description

- [ ] Find alternatives
- [ ] Collect and describe them here

## Reference

See parent task

**Comment by Krakazybik** [comment]
[reaflow](https://github.com/reaviz/reaflow)

Особенности:
- Кастомизация
![image](https://user-images.githubusercontent.com/1334019/147373275-9e2830de-5c1d-444a-adf6-27d0a2d19538.png)
![image](https://user-images.githubusercontent.com/1334019/147373283-7585dd39-1879-47b6-80ce-bb410088f374.png)
- Возможность создания пресетов по слоями/сегментам

https://user-images.githubusercontent.com/1334019/147373304-bb59f4e5-1b26-4df2-bcfc-65fc9e8725c9.mp4


-  Undo/redo, приятный бонус


https://user-images.githubusercontent.com/1334019/147373345-d8a6aee5-232c-4f5e-bff2-e2d69f5939ea.mp4

- Пример с DnD


https://user-images.githubusercontent.com/1334019/147373396-ea986c22-4a16-4e39-b1b9-b8542319dd14.mp4

- zoom


https://user-images.githubusercontent.com/1334019/147373417-29596029-1836-46e0-95b0-c2e06ce8f7e5.mp4

- Ну и собственно "я у мамы дезигнер"
![image](https://user-images.githubusercontent.com/1334019/147373429-977c660b-84f1-4969-889f-513a2087cc6c.png)

**Comment by Krakazybik** [comment]
[react-dnd-treeview](https://www.npmjs.com/package/@minoru/react-dnd-treeview)
Сразу папочки! JSON'чик из коробки.
![image](https://user-images.githubusercontent.com/1334019/147373672-e86e2fa0-f82e-4dcb-b043-3c107003f12c.png)
Пощупать вот здесь https://codesandbox.io/s/placeholder-js-xhu2j

**Comment by azinit** [comment]
> react-dnd-treeview
Сразу папочки! JSON'чик из коробки.

Саша вродь его и пробовал как раз с файловой структурой организовать, но вродь какие то проблемы были

@AlexandrHoroshih уточнишь?

**Comment by Krakazybik** [comment]
[RC-Tree](https://www.npmjs.com/package/rc-tree)
Немного страшенькая, но это дело исправимо, из плюсов(а может быть и нет), часто вроде релизица.
[Дёмка](https://tree-react-component.vercel.app/demo/animation-draggable)

**Comment by Krakazybik** [comment]
[ANTD](https://ant.design/components/tree/#components-tree-demo-draggable)
Из плюсов - темы и другие плюшки анта.

https://user-images.githubusercontent.com/1334019/147373836-df122d9c-96c9-4490-b140-da0b7d8b961f.mp4

**Comment by azinit** [comment]
@Krakazybik JFYI - альтернативы можно искать не сколько "техническая реализация", а похожие "редакторы" с деревьями/структурами/нодами и т.п.

(как вот выше кидал примеры ты)

Но то что ты примеры еще реализаций тут кидаешь - тож немаловажно
(хотя там @AlexandrHoroshih уже и заложил основы, но если найдется что лучше - you're welcome 🤔 )

**Comment by AlexandrHoroshih** [comment]
> Саша вродь его и пробовал как раз с файловой структурой организовать, но вродь какие то проблемы были

Пробовал немного, основной моменты, которые напрягали:
1. фокус представления на файловой структуре, в то время как в моем представлении это должны быть именно смысловые блоки: слои, слайсы, сегменты и то, как они в эту слоистую структуру складываются.
По этой же причине Tree компонент из анта и reaflow на мой взгляд тоже несколько мимо идут
Практически идеальный вариант: https://frontend-collective.github.io/react-sortable-tree/?path=/story/basics--modify-nodes
Но вид нод хотелось бы чуть другой + эта штука уже давно заброшена 😿 

2. в этом react-dnd-treeview (и большинстве других решений) внутри юзается react-dnd - Тяжелое, внутри накручено куча всякого поверх аж целого редакса - оно конечно самое стабильное для реакта сейчас, но хотелось бы, чтобы структуру можно было накидать/покрутить с мобилки, так что задача становится немного критичной к производительным анимациям в этом месте
Поэтому я посмотрел в сторону https://github.com/clauderic/dnd-kit - в сорсах видно, что много утащили с того же react-dnd, но сама либа весит поменьше и на моей мобилке их демки работали получше с драг-н-дропом

**Comment by Krakazybik** [comment]
Ещё flow https://reactflow.dev/examples/

https://user-images.githubusercontent.com/1334019/147374004-7316e1f2-1117-4d50-bc17-1e3a97ba1641.mp4


https://user-images.githubusercontent.com/1334019/147374005-2dac1869-e8c5-40e7-8d68-2b87ef77dc05.mp4


https://user-images.githubusercontent.com/1334019/147374007-c4a33857-0264-4256-a3a2-6b9e5f78db5f.mp4


https://user-images.githubusercontent.com/1334019/147374008-6d23a08c-7bb7-4cbd-8593-aeefc2e28888.mp4

**Comment by AlexandrHoroshih** [comment]
У меня, кстати, все скринкасты мертвые 🤔 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/32790736/147374292-4232768d-ad8f-47a2-9692-0cdee5a69fd3.png">

**Comment by azinit** [comment]
> У меня, кстати, все скринкасты мертвые 🤔

🤔 

![image](https://user-images.githubusercontent.com/42924400/147374311-06de5e45-5647-4bb9-887c-475ddc48b2bf.png)

**Comment by AlexandrHoroshih** [comment]
> Практически идеальный вариант: https://frontend-collective.github.io/react-sortable-tree/?path=/story/basics--modify-nodes
Но вид нод хотелось бы чуть другой + эта штука уже давно заброшена 😿
Хотел перетащить их наработки в ту платформу, что в репле уже собрал, но руки не доходят пока

Также мне оч нравится вариант из примеров самого @dnd-kit:
https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/examples-tree-sortable--all-features

**Comment by Krakazybik** [comment]
[SortableJS](http://sortablejs.github.io/Sortable/)
К нему есть реактовый, но который полумертвый
Пока это всё, остальное либо мертво, либо убого.
