### ISSUE TITLE
REPL: [tree] Impl Drag&Drop for nesting structure

### ISSUE THREAD

**Issue by azinit** [feature-sliced/repl#5]
## Description

Impl basic nesting of tree nodes by Drag-n-Drop

## Reference

See parent task

As reference (but impl by your own)

![image](https://user-images.githubusercontent.com/42924400/147372762-9c7c6913-1179-493b-8530-59bbf025953c.png)

**Comment by Krakazybik** [comment]
@AlexandrHoroshih @azinit  Возник вопрос =) Какое поведение должно быть при перетаскивании родительского элемента в его потомка?
Т.к. на данный момент они схлопываются и открывают черную дыру :laughing: 


Я сейчас сделал 2 варианта:
- Поднятие всех потомков на уровень родительского и после этого перемещение родителя уже в потомка.
```sh
└── node
    └── current
        ├── node
        |     ├── node
        |     ├── node
        |     └── target
        |
        └── node
```

```sh
└── node
    ├── node
    |     ├── node
    |     ├── node
    |     └── target
    |          └── current
    └── node
```

- Свап родителя и потомка.

```sh
└── node
    └── current
        ├── node
        |     ├── node
        |     ├── node
        |     └── target
        |
        └── node
```

```sh
└── node
    └── target
        ├── node
        |     ├── node
        |     ├── node
        |     └── current
        |
        └── node
```

**Comment by AlexandrHoroshih** [comment]
@Krakazybik 
Оба варианта, на мой взгляд, не туда 🤔

Я думаю, будет вернее, если дети будут перемещаться вместе с родителем - т.е. положить родителя в потомка должно быть невозможно

Референс:
https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/examples-tree-sortable--all-features

**Comment by Krakazybik** [comment]
> Я думаю, будет вернее, если дети будут перемещаться вместе с родителем - т.е. положить родителя в потомка должно быть невозможно

Окей =)
